# Generated by Django 4.2.25 on 2025-10-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('product_info', 'Product Information'), ('bulk_order', 'Bulk Order Quote'), ('custom_branding', 'Custom Branding'), ('partnership', 'Partnership Opportunity'), ('complaint', 'Complaint/Feedback'), ('other', 'Other')], max_length=50)),
                ('product_interest', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('best_time_to_call', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=300)),
                ('business_type', models.CharField(choices=[('retail_store', 'Retail Store'), ('supermarket', 'Supermarket/Chain'), ('hotel_resort', 'Hotel/Resort'), ('spa_salon', 'Spa/Salon'), ('temple_ashram', 'Temple/Ashram'), ('yoga_studio', 'Yoga Studio/Wellness Center'), ('distributor', 'Distributor/Wholesaler'), ('online_seller', 'Online Seller/E-commerce'), ('event_planner', 'Event Planner'), ('corporate', 'Corporate Office'), ('other', 'Other')], max_length=50)),
                ('years_in_business', models.CharField(blank=True, max_length=50)),
                ('business_website', models.URLField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('alternative_contact', models.CharField(blank=True, max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('any', 'Any of the Above')], default='email', max_length=20)),
                ('best_time_to_reach', models.CharField(blank=True, max_length=200)),
                ('product_interests', models.TextField(help_text='Products interested in')),
                ('tissue_variant', models.CharField(blank=True, max_length=200)),
                ('tissue_fragrance', models.CharField(blank=True, max_length=200)),
                ('tissue_quantity', models.CharField(blank=True, max_length=200)),
                ('dhoop_pack_size', models.CharField(blank=True, max_length=200)),
                ('dhoop_fragrance', models.CharField(blank=True, max_length=200)),
                ('dhoop_quantity', models.CharField(blank=True, max_length=200)),
                ('order_frequency', models.CharField(blank=True, choices=[('one_time', 'One-Time Order'), ('monthly', 'Monthly Regular Orders'), ('quarterly', 'Quarterly Orders'), ('biannual', 'Bi-Annual Orders'), ('trial_based', 'Will Decide Based on Trial Order')], max_length=50)),
                ('timeline', models.CharField(blank=True, help_text='When do they need it?', max_length=100)),
                ('sample_order_first', models.BooleanField(default=False)),
                ('custom_branding_required', models.BooleanField(default=False)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('has_logo', models.BooleanField(default=False)),
                ('branding_requirements', models.TextField(blank=True)),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='quote_logos/')),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_pin', models.CharField(max_length=10)),
                ('delivery_address_type', models.CharField(blank=True, max_length=100)),
                ('special_delivery_requirements', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('payment_terms_preference', models.CharField(blank=True, max_length=200)),
                ('how_heard_about_us', models.CharField(blank=True, max_length=200)),
                ('specific_requirements', models.TextField(blank=True)),
                ('wants_call_discussion', models.BooleanField(default=False)),
                ('agreed_to_contact', models.BooleanField(default=True)),
                ('wants_updates', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('quoted', 'Quote Sent'), ('negotiating', 'In Negotiation'), ('accepted', 'Quote Accepted'), ('rejected', 'Quote Rejected'), ('closed', 'Closed')], default='new', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('quantity_needed', models.CharField(help_text="e.g., '500-1000 packs'", max_length=100)),
                ('preferred_variant', models.CharField(blank=True, max_length=200)),
                ('fragrance_preference', models.CharField(blank=True, max_length=200)),
                ('custom_branding_required', models.BooleanField(default=False)),
                ('delivery_location', models.CharField(max_length=300)),
                ('additional_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote Sent'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
