# Generated by Django 4.2.25 on 2025-10-13 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('contact', 'Contact Message'), ('quote', 'Quote Request')], max_length=20)),
                ('reply_from', models.EmailField(help_text='From email address', max_length=254)),
                ('reply_to', models.EmailField(help_text='Recipient email address', max_length=254)),
                ('reply_subject', models.CharField(max_length=300)),
                ('reply_message', models.TextField()),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, help_text='Error message if email failed to send')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment (e.g., quote PDF)', null=True, upload_to='inquiry_replies/')),
                ('contact_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inquiries.contactmessage')),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inquiries.quoterequest')),
                ('replied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inquiry Reply',
                'verbose_name_plural': 'Inquiry Replies',
                'ordering': ['-replied_at'],
            },
        ),
    ]
