---
# cPanel Deployment Configuration for nageshcare.com
# Uses rsync for efficient deployment - only copies changed files

deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/wrgccpiz/public_html/nageshcare

    # Ensure deployment directory exists
    - /bin/mkdir -p $DEPLOYPATH

    # Copy all files from repository to deployment path
    - /bin/cp -R * $DEPLOYPATH/ 2>/dev/null || true

    # Copy hidden files (.htaccess, etc.)
    - /bin/cp .htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp .gitignore $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp .env.example $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp .env.production $DEPLOYPATH/ 2>/dev/null || true

    # Create necessary directories if they don't exist
    - /bin/mkdir -p $DEPLOYPATH/media
    - /bin/mkdir -p $DEPLOYPATH/staticfiles
    - /bin/mkdir -p $DEPLOYPATH/logs
    - /bin/mkdir -p $DEPLOYPATH/tmp

    # Set proper permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH/manage.py
    - /bin/chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH/static 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH/media 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH/staticfiles 2>/dev/null || true

    # Restart the Python app by touching passenger_wsgi.py
    - /bin/touch $DEPLOYPATH/passenger_wsgi.py
    - /bin/touch $DEPLOYPATH/tmp/restart.txt 2>/dev/null || true
