---
# cPanel Deployment Configuration for nageshcare.com
# This file enables Git Version Control deployment in cPanel
# Simplified version - only copies files, run setup commands manually

deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/wrgccpiz/public_html/nageshcare

    # Copy all files to deployment directory
    - /bin/cp -R * $DEPLOYPATH

    # Copy hidden files (.htaccess, etc.) - .env should already exist
    - /bin/cp -R .[^.]* $DEPLOYPATH 2>/dev/null || true

    # Set correct permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || true

    # Restart the Python app
    - mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
