---
# cPanel Deployment Configuration for nageshcare.com
# Uses rsync for efficient deployment - only copies changed files

deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/wrgccpiz/public_html/nageshcare

    # Use rsync to copy only changed files (much faster!)
    # Exclude large/unnecessary directories
    - >
      /usr/bin/rsync -av --delete
      --exclude='.git'
      --exclude='*.pyc'
      --exclude='__pycache__'
      --exclude='.env'
      --exclude='db.sqlite3'
      --exclude='media/'
      --exclude='staticfiles/'
      --exclude='logs/'
      --exclude='*.log'
      ./ $DEPLOYPATH/

    # Restart the Python app
    - /bin/touch $DEPLOYPATH/tmp/restart.txt 2>/dev/null || true
