---
# cPanel Deployment Configuration for NageshCare
# This file configures automatic deployment from Git repository to cPanel

deployment:
  tasks:
    # Step 1: Deploy all files to the application directory
    - export DEPLOYPATH=/home/wrgccpiz/public_html/nageshcare

    # Step 2: Copy all repository files to deployment path
    - /bin/cp -R * $DEPLOYPATH

    # Step 3: Copy only specific hidden files (not all)
    # DO NOT copy .htaccess (it goes in parent directory, not here)
    # DO NOT copy .git directory or backup files
    - /bin/cp .gitignore $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .env $DEPLOYPATH 2>/dev/null || true

    # Step 4: Navigate to deployment directory
    - cd $DEPLOYPATH

    # Step 5: Activate virtual environment and install/update dependencies
    - source /home/wrgccpiz/virtualenv/public_html/nageshcare/3.12/bin/activate
    - pip install -r requirements.txt --upgrade

    # Step 6: Run Django management commands
    - python manage.py migrate --noinput
    - python manage.py collectstatic --noinput --clear

    # Step 7: Create necessary directories
    - mkdir -p logs media staticfiles

    # Step 8: Set proper permissions
    - chmod 755 $DEPLOYPATH
    - chmod 755 $DEPLOYPATH/manage.py
    - chmod -R 755 $DEPLOYPATH/static 2>/dev/null || true
    - chmod -R 755 $DEPLOYPATH/staticfiles 2>/dev/null || true
    - chmod -R 755 $DEPLOYPATH/media 2>/dev/null || true
    - chmod 600 $DEPLOYPATH/.env 2>/dev/null || true

    # Step 9: Restart the Passenger application
    - touch $DEPLOYPATH/passenger_wsgi.py

    # Step 10: Log deployment
    - echo "Deployment completed at $(date)" >> $DEPLOYPATH/logs/deployment.log
