# Generated by Django 4.2.25 on 2025-10-13 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('products', 'Products Page'), ('product_detail', 'Product Detail Page')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('primary_button_text', models.CharField(max_length=100)),
                ('primary_button_url', models.CharField(max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200)),
                ('background_color', models.CharField(default='gradient', help_text='CSS class or color', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call To Action',
                'verbose_name_plural': 'Call To Actions',
                'ordering': ['page_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Bootstrap icon class (e.g., bi bi-shop)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Industry',
                'verbose_name_plural': 'Client Industries',
                'ordering': ['order', 'industry_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Happy Clients', max_length=100)),
                ('value', models.CharField(help_text='e.g., 100+, 4.9/5, 500+', max_length=50)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(choices=[('home-testimonials', 'Home - Testimonials Section'), ('footer', 'Footer'), ('about', 'About Page')], default='home-testimonials', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Statistic',
                'verbose_name_plural': 'Company Statistics',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_identifier', models.CharField(choices=[('why-choose-us', 'Why Choose Us'), ('values', 'Core Values'), ('benefits', 'Benefits'), ('how-we-work', 'How We Work'), ('product-benefits', 'Product Benefits'), ('about-vision-mission', 'About - Vision & Mission')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Bootstrap icon class (e.g., bi bi-award-fill)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Card',
                'verbose_name_plural': 'Feature Cards',
                'ordering': ['section_identifier', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('products', 'Products Page')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('button1_text', models.CharField(blank=True, max_length=100)),
                ('button1_url', models.CharField(blank=True, max_length=200)),
                ('button2_text', models.CharField(blank=True, max_length=100)),
                ('button2_url', models.CharField(blank=True, max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='cms/hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['page_name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_role', models.CharField(help_text='e.g., Retail Store Owner', max_length=200)),
                ('customer_location', models.CharField(help_text='e.g., Mumbai', max_length=200)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('testimonial_text', models.TextField()),
                ('avatar_initials', models.CharField(help_text='2-letter initials for avatar (e.g., RK)', max_length=2)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('products', 'Products Page')], max_length=50)),
                ('section_identifier', models.CharField(help_text='Unique identifier for this content block (e.g., intro-text, company-story)', max_length=100)),
                ('content_key', models.SlugField(help_text='Unique key for template usage', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(help_text='Rich text content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Text Content',
                'verbose_name_plural': 'Text Content',
                'ordering': ['page_name', 'section_identifier'],
            },
        ),
        migrations.CreateModel(
            name='TrustIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('icon_class', models.CharField(help_text='Bootstrap icon class (e.g., bi bi-gift-fill)', max_length=100)),
                ('position', models.CharField(choices=[('hero', 'Hero Section'), ('footer', 'Footer'), ('sidebar', 'Sidebar')], default='hero', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trust Indicator',
                'verbose_name_plural': 'Trust Indicators',
                'ordering': ['position', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='NageshCare', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_whatsapp', models.CharField(max_length=20)),
                ('email_primary', models.EmailField(max_length=254)),
                ('email_support', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True, help_text='Format: https://wa.me/919876543210')),
                ('business_hours', models.CharField(default='Mon-Sat: 9:00 AM - 6:00 PM', max_length=200)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('cin_number', models.CharField(blank=True, max_length=30)),
                ('msme_number', models.CharField(blank=True, max_length=30)),
                ('established_year', models.CharField(blank=True, max_length=4)),
                ('default_meta_description', models.TextField(blank=True, max_length=300)),
                ('default_meta_keywords', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='cms/media/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
