# Generated by Django 4.2.25 on 2025-10-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='content_alignment',
            field=models.CharField(choices=[('left', 'Left Aligned'), ('center', 'Center Aligned'), ('right', 'Right Aligned')], default='left', help_text='Text alignment for hero content', max_length=20),
        ),
    ]
