# Generated by Django 4.2.25 on 2025-10-13 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_herosection_content_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_palette', models.CharField(choices=[('default', 'Default (Teal & Golden)'), ('nature', 'Nature (Forest Green & Cream)'), ('professional', 'Professional (Dark & Blue-Gray)'), ('custom', 'Custom')], default='default', help_text='Select a pre-configured palette or customize your own', max_length=20)),
                ('primary_color', models.CharField(default='#264653', help_text='Primary brand color (e.g., #264653)', max_length=7)),
                ('primary_hover', models.CharField(default='#1A4D59', help_text='Primary hover state', max_length=7)),
                ('secondary_color', models.CharField(default='#E9C46A', help_text='Secondary/accent color (e.g., #E9C46A)', max_length=7)),
                ('secondary_hover', models.CharField(default='#D4AF37', help_text='Secondary hover state', max_length=7)),
                ('accent_color', models.CharField(default='#2A9D8F', help_text='Accent color for badges, highlights', max_length=7)),
                ('background_light', models.CharField(default='#F8F9FA', help_text='Light background (sections)', max_length=7)),
                ('background_dark', models.CharField(default='#1A3540', help_text='Dark background (footer)', max_length=7)),
                ('text_primary', models.CharField(default='#333333', help_text='Main body text color', max_length=7)),
                ('text_secondary', models.CharField(default='#6C757D', help_text='Muted/secondary text', max_length=7)),
                ('border_light', models.CharField(default='#F0F0F0', help_text='Light borders', max_length=7)),
                ('border_medium', models.CharField(default='#CED4DA', help_text='Medium borders', max_length=7)),
                ('font_heading', models.CharField(default='Inter', help_text='Font family for headings (h1-h6)', max_length=100)),
                ('font_heading_weight', models.IntegerField(default=700, help_text='Font weight for headings')),
                ('font_body', models.CharField(default='Roboto', help_text='Font family for body text', max_length=100)),
                ('font_body_weight', models.IntegerField(default=400, help_text='Font weight for body text')),
                ('font_size_base', models.CharField(default='16px', help_text='Base font size', max_length=10)),
                ('font_size_h1', models.CharField(default='2.5rem', help_text='H1 size', max_length=10)),
                ('font_size_h2', models.CharField(default='2rem', help_text='H2 size', max_length=10)),
                ('font_size_h3', models.CharField(default='1.75rem', help_text='H3 size', max_length=10)),
                ('font_size_h4', models.CharField(default='1.5rem', help_text='H4 size', max_length=10)),
                ('font_size_h5', models.CharField(default='1.25rem', help_text='H5 size', max_length=10)),
                ('font_size_h6', models.CharField(default='1rem', help_text='H6 size', max_length=10)),
                ('border_radius', models.CharField(default='8px', help_text='Default border radius', max_length=10)),
                ('box_shadow_default', models.CharField(default='0 4px 6px rgba(0, 0, 0, 0.08)', help_text='Default box shadow', max_length=100)),
                ('box_shadow_hover', models.CharField(default='0 8px 15px rgba(0, 0, 0, 0.15)', help_text='Hover box shadow', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
