# Generated by Django 4.2.25 on 2025-10-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='footer_bg',
            field=models.CharField(default='#1A3540', help_text='Footer background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_heading',
            field=models.CharField(default='#E9C46A', help_text='Footer section headings', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_icon',
            field=models.CharField(default='#E9C46A', help_text='Footer icons (non-social)', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_link',
            field=models.CharField(default='#B8C5CC', help_text='Footer links', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_link_hover',
            field=models.CharField(default='#E9C46A', help_text='Footer link hover', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_text',
            field=models.CharField(default='#B8C5CC', help_text='Footer body text', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='icon_default',
            field=models.CharField(default='#264653', help_text='Default icon color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='icon_feature',
            field=models.CharField(default='#264653', help_text='Feature card icons', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='icon_hover',
            field=models.CharField(default='#2A9D8F', help_text='Icon hover state', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='icon_trust',
            field=models.CharField(default='#E9C46A', help_text='Trust indicator icons', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_bg',
            field=models.CharField(default='#FFFFFF', help_text='Main navigation background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_link',
            field=models.CharField(default='#333333', help_text='Navigation link color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_link_active',
            field=models.CharField(default='#264653', help_text='Active nav link color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_link_hover',
            field=models.CharField(default='#264653', help_text='Nav link hover color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='section_subtitle',
            field=models.CharField(default='#2A9D8F', help_text='Section subtitle/eyebrow text', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_muted',
            field=models.CharField(default='#6C757D', help_text='Muted/helper text', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='topbar_bg',
            field=models.CharField(default='#264653', help_text='Top info bar background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='topbar_link',
            field=models.CharField(default='#FFFFFF', help_text='Top bar link color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='topbar_link_hover',
            field=models.CharField(default='#E9C46A', help_text='Top bar link hover', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='topbar_text',
            field=models.CharField(default='#FFFFFF', help_text='Top bar text color', max_length=7),
        ),
    ]
