# Generated by Django 4.2.25 on 2025-10-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_themesettings_footer_bg_themesettings_footer_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='metric3_icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class for third metric', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='metric3_label',
            field=models.CharField(blank=True, help_text='Third metric label (e.g., "Obligation")', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='metric3_value',
            field=models.CharField(blank=True, help_text='Third metric value (e.g., "Zero")', max_length=50),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('products', 'Products Page'), ('product_detail', 'Product Detail Page'), ('request-quote', 'Request Quote Page')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='section_identifier',
            field=models.CharField(choices=[('why-choose-us', 'Why Choose Us'), ('values', 'Core Values'), ('benefits', 'Benefits'), ('how-we-work', 'How We Work'), ('product-benefits', 'Product Benefits'), ('about-vision-mission', 'About - Vision & Mission'), ('quote-inclusions', 'Request Quote - Quote Inclusions')], max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('products', 'Products Page'), ('request-quote', 'Request Quote Page')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('products', 'Products Page'), ('request-quote', 'Request Quote Page')], max_length=50),
        ),
    ]
