# Generated by Django 4.2.25 on 2025-10-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_herosection_metric3_icon_herosection_metric3_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP server (e.g., smtp.gmail.com)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password or app password', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='SMTP username/email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP port (587 for TLS, 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_reply_signature',
            field=models.TextField(blank=True, default='Best regards,\nNageshCare Team\nwww.nageshcare.com', help_text='Email signature for replies'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption'),
        ),
    ]
