# Generated by Django 4.2.25 on 2025-10-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_sitesettings_email_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_float_enabled',
            field=models.BooleanField(default=True, help_text='Enable floating WhatsApp button'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_float_message',
            field=models.TextField(default="Hi, I'm interested in your wholesale products. Please share more details.", help_text='Default message text for WhatsApp chat'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_float_position_bottom',
            field=models.IntegerField(default=100, help_text='Bottom position in pixels'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_float_position_right',
            field=models.IntegerField(default=20, help_text='Right position in pixels'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_float_show_on_desktop',
            field=models.BooleanField(default=True, help_text='Show on desktop/tablet'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_float_show_on_mobile',
            field=models.BooleanField(default=False, help_text='Show on mobile devices'),
        ),
    ]
