# Generated by Django 4.2.25 on 2025-10-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short catchy tagline', max_length=200)),
                ('short_description', models.TextField(help_text='Brief description for catalog page')),
                ('full_description', models.TextField(help_text='Detailed description for product detail page')),
                ('features', models.TextField(blank=True, help_text='Product features, one per line')),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('minimum_order_quantity', models.CharField(blank=True, help_text="e.g., '500 packs' or '1,000 sticks'", max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_coming_soon', models.BooleanField(default=False, help_text='Mark as coming soon')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text="e.g., 'Pocket Pack (100 sheets)', 'Retail Pack (20 sticks)'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications, one per line')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['order', 'variant_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_primary', models.BooleanField(default=False, help_text='Main product image')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FragranceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Lavender Fresh', 'Sandalwood Supreme'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text="e.g., 'Traditional Sacred', 'Contemporary Wellness'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrances', to='products.product')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
